<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter_Button</name>
   <tag></tag>
   <elementGuidId>dad6fe8d-c3bc-4a6e-8d93-bb6d9b7dba6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-keypad-btn.dcg-btn-short-blue.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[3]/div/div[4]/div[13]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87c430cb-e98a-4ba4-b9cd-88d365ea7161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39826c84-d48c-4a2a-96cd-4182497a88e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-keypad-btn dcg-btn-short-blue dcg-hovered</value>
      <webElementGuid>7de94b63-2d69-43e8-9457-c9c0bc0212aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcg-command</name>
      <type>Main</type>
      <value>enter</value>
      <webElementGuid>635ab687-bdb7-4d7b-9c9a-f729d540564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>75a115ce-b0d5-45fc-81f5-f133efb52649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-matrix-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-matrix-main-wrapper dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-matrix-main dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad-container dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-row dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-btn-container dcg-hovered&quot;]/span[@class=&quot;dcg-keypad-btn dcg-btn-short-blue dcg-hovered&quot;]</value>
      <webElementGuid>26a5fec2-6009-448d-a88a-a1b8a9c6220c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[3]/div/div[4]/div[13]/span</value>
      <webElementGuid>8dfe69fc-af05-4ed2-b0e6-74e7ffa2d12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−'])[2]/following::span[1]</value>
      <webElementGuid>4a0e9137-9043-44c7-816c-870300877388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='negative'])[1]/following::span[3]</value>
      <webElementGuid>1db9e782-ca8a-45c6-b2b2-2576385800f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[13]/span</value>
      <webElementGuid>9fd4cffc-247c-41da-bfe6-0a715658153c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
