<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HasilPerhitungan2</name>
   <tag></tag>
   <elementGuidId>c1a85688-4cd5-4c32-934e-04977d3926b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-mq-root-block.dcg-hovered.dcg-mq-hasCursor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div[2]/div[2]/div[2]/span/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;=14&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39b8e339-2580-420b-af91-f34ee59a5c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-mq-root-block dcg-hovered dcg-mq-hasCursor</value>
      <webElementGuid>778d8003-6bb4-4e30-9dc8-4419b5b3dc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fdb1df2f-e64e-4a77-a059-58ee65d0f159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>=14​</value>
      <webElementGuid>f9975fc7-0fae-4973-a712-68715ff9c3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-matrix-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-matrix-main-wrapper dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-matrix-main dcg-hovered&quot;]/div[@class=&quot;dcg-matrix-list-container dcg-hovered&quot;]/div[@class=&quot;dcg-matrix-list dcg-hovered&quot;]/div[@class=&quot;dcg-latex-expression dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-evaluation dcg-number-evaluation dcg-hovered&quot;]/span[@class=&quot;dcg-output dcg-hovered&quot;]/div[@class=&quot;dcg-mq-math-mode dcg-static-mathquill-view dcg-hovered&quot;]/span[@class=&quot;dcg-mq-root-block dcg-hovered dcg-mq-hasCursor&quot;]</value>
      <webElementGuid>440bd95b-6b9f-4b7d-b003-dbd52e758f69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div[2]/div[2]/span/div/span[2]</value>
      <webElementGuid>328d9ce2-0b00-4d76-aa4f-7dbe1ed2f4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='equals 14'])[1]/following::span[1]</value>
      <webElementGuid>49087b4a-3c9d-4b7b-b43e-5b7be1c79f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[2]/following::span[4]</value>
      <webElementGuid>da436f72-37dc-463e-b9a1-eafde67be4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/span[2]</value>
      <webElementGuid>0fcac3e9-8880-4937-ac72-6772b9bd2d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '=14​' or . = '=14​')]</value>
      <webElementGuid>a835fa09-1dd8-4d0c-846a-4fbab8758f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
