<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalculatorScientific</name>
   <tag></tag>
   <elementGuidId>334e8276-38dc-4440-bd37-9eb856879975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.dcg-shared-product-icon.dcg-icon-matrix.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='dcg-main-content-region']/div/section[2]/div/div/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Matrix&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e32ed978-e0da-40cc-b69e-c41bce1bab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-shared-product-icon dcg-icon-matrix dcg-hovered</value>
      <webElementGuid>3fd3cd20-d81f-4fd2-b532-f8fb1450f642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92f92c95-315c-4959-bf38-c791e4c7a13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dcg-main-content-region&quot;)/div[@class=&quot;dcg-frontpage-landing dcg-hovered&quot;]/section[@class=&quot;dcg-frontpage-landing-section dcg-frontpage-landing-section--one-column dcg-frontpage-landing-section--tools dcg-hovered&quot;]/div[@class=&quot;dcg-frontpage-landing-section__content dcg-hovered&quot;]/div[@class=&quot;dcg-frontpage-landing-tools dcg-hovered&quot;]/a[@class=&quot;dcg-frontpage-landing-tools__link dcg-shared-product-icon-container dcg-hovered&quot;]/i[@class=&quot;dcg-shared-product-icon dcg-icon-matrix dcg-hovered&quot;]</value>
      <webElementGuid>91b4536d-9061-48aa-9f65-3731861f3635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='dcg-main-content-region']/div/section[2]/div/div/a[4]/i</value>
      <webElementGuid>57905546-c994-4685-b10b-60d9329936f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>519a1b31-e535-45aa-b2cd-239e0ab11d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='dcg-main-content-region']/div/section[2]/div/div/a[2]/i</value>
      <webElementGuid>82262927-76b7-442d-bee1-49529bb5039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>142ef5f2-78e7-4723-a0f8-a7f958254a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
