<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number4_Button</name>
   <tag></tag>
   <elementGuidId>3f2960e3-2a19-4f0a-87a9-11d2564bef3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-keypad-btn.dcg-btn-dark-on-gray.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;4&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c178b5fa-4a26-4693-8ae2-76f7b5ec4bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88631cdb-a309-46bb-9e51-3d7d029415a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-keypad-btn dcg-btn-dark-on-gray dcg-hovered</value>
      <webElementGuid>53b59b2d-bd40-44c1-ab96-e66db3474859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcg-command</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2e26cc3f-4622-4fc7-90e3-aa03eacf0980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>772598fd-d9a5-4d46-bbb3-db73844295a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>ef83d328-64b4-4d6d-9586-1f6d96947f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-calculator-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-basic-main-wrapper dcg-scientific-calculator dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-basic-main dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad-container dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-row dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-btn-container dcg-hovered&quot;]/span[@class=&quot;dcg-keypad-btn dcg-btn-dark-on-gray dcg-hovered&quot;]</value>
      <webElementGuid>534a0f2a-77ac-4f84-8ebc-75da6f92fbf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[5]/span</value>
      <webElementGuid>4502beb3-d600-45e3-a24e-106cd014724a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='π'])[1]/following::span[1]</value>
      <webElementGuid>df02ff20-b283-43f3-bf4d-2bdf672b5d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pi'])[1]/following::span[3]</value>
      <webElementGuid>36cff84b-265f-4670-ba81-9c42252a673f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='times'])[1]/preceding::span[15]</value>
      <webElementGuid>e42cb2a9-c009-439a-b8a3-785b4a7f76d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[16]</value>
      <webElementGuid>e58b60ce-007c-4a3c-9d90-5e7e38ef1f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/span</value>
      <webElementGuid>42d95608-bba4-4fbb-a486-ff1268d8035c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '44' or . = '44')]</value>
      <webElementGuid>f838191d-1f10-4347-890a-d24afe2a5fe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
