<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>times_Button</name>
   <tag></tag>
   <elementGuidId>5caea0c9-7418-4a3c-b98c-a4ebe9c07b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-keypad-btn.dcg-btn-light-on-gray.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[8]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Times&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fd25393-5769-4160-88e3-ad158c00a1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49736550-8202-4fb9-8cbf-9175ca5e4cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-keypad-btn dcg-btn-light-on-gray dcg-hovered</value>
      <webElementGuid>fce7a5ee-4c20-44e2-893b-0a8c93da2dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcg-command</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>edeb7b0e-f888-43e3-a4dd-966d7fc19af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Times</value>
      <webElementGuid>f8b911c2-23e1-44ee-85c4-d4aa84a9e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>times×</value>
      <webElementGuid>361e49c1-15ce-4c54-a5cd-adbf7cf1f6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-calculator-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-basic-main-wrapper dcg-scientific-calculator dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-basic-main dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad-container dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-row dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-btn-container dcg-hovered&quot;]/span[@class=&quot;dcg-keypad-btn dcg-btn-light-on-gray dcg-hovered&quot;]</value>
      <webElementGuid>2b6fb224-16d2-4c5b-9c34-2f14c372dffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[8]/span</value>
      <webElementGuid>c03badb5-3cc3-4316-ae73-63179eb9ddf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='π'])[1]/following::span[16]</value>
      <webElementGuid>077bc02d-bff6-4d76-9577-734633afaa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pi'])[1]/following::span[18]</value>
      <webElementGuid>c7f6a9ad-2142-4a2c-b0fe-ca42b9b51848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[8]/span</value>
      <webElementGuid>65565e39-9a6e-4f99-a0cd-a2cf30351454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'times×' or . = 'times×')]</value>
      <webElementGuid>34f1d652-e79a-4f72-a4cd-736bab59b3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
