<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NewMatrix_button</name>
   <tag></tag>
   <elementGuidId>c9ffa30a-9d9f-4a6e-b5cf-a4f8afeba6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dcg-keypad-control-btn.dcg-menu-btn.dcg-btn-blue.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New Matrix&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d11cdf5-4dec-43f9-8fe3-41fea08d0552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-keypad-control-btn dcg-menu-btn dcg-btn-blue dcg-hovered</value>
      <webElementGuid>23bacbc8-e93e-4ee7-869a-51e3a7c83832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4567a15-530e-4c35-8644-dfdab5fea8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>135ce6e3-ddf8-4423-a5fb-e00bc5aa6c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New Matrix</value>
      <webElementGuid>b33f0d1f-986f-40f2-9e20-f49c401e4c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcg-command</name>
      <type>Main</type>
      <value>add-matrix</value>
      <webElementGuid>8e624c77-c930-4381-8051-c3f666f102bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>713fea41-7113-4f71-accc-62693ddbeb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Matrix</value>
      <webElementGuid>b29ac414-d7e9-4a82-b7bf-c09af0340555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-matrix-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-matrix-main-wrapper dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-matrix-main dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-control-bar dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-control-bar-contents dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-control-btn dcg-menu-btn dcg-btn-blue dcg-hovered&quot;]</value>
      <webElementGuid>e9e3d7c6-c338-4fb0-95af-2a7ac731dc6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[2]/div/div</value>
      <webElementGuid>e8ccd88a-8d46-4475-82f9-7631cec6e5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[17]</value>
      <webElementGuid>cec6531a-cf5a-4e63-94ed-5546aac58137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[1]/following::div[26]</value>
      <webElementGuid>c47526b4-1cdc-4398-b13f-b1a763d8b64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear all'])[1]/preceding::div[4]</value>
      <webElementGuid>3f536cf4-0a64-4f4e-b0df-ee4aba9cdcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>227b0a45-fa67-4af3-a8c1-36db279229c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New Matrix' or . = 'New Matrix')]</value>
      <webElementGuid>4967b9b9-dd40-4052-833a-b5b43a9993da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
