<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Matrix_Calculator</name>
   <tag></tag>
   <elementGuidId>7264745b-b5f0-45fd-9b43-6e0118884fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='dcg-main-content-region']/div/section[2]/div/div/a[4]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.dcg-shared-product-icon.dcg-icon-matrix.dcg-hovered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Matrix&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f47339ea-2aa9-4a99-b02b-66ce15b7d70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-shared-product-icon dcg-icon-matrix dcg-hovered</value>
      <webElementGuid>bc5a2eb4-b980-46e9-9f30-ee26f5303444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30ccb087-fe90-4621-805b-caf062689382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dcg-main-content-region&quot;)/div[@class=&quot;dcg-frontpage-landing dcg-hovered&quot;]/section[@class=&quot;dcg-frontpage-landing-section dcg-frontpage-landing-section--one-column dcg-frontpage-landing-section--tools dcg-hovered&quot;]/div[@class=&quot;dcg-frontpage-landing-section__content dcg-hovered&quot;]/div[@class=&quot;dcg-frontpage-landing-tools dcg-hovered&quot;]/a[@class=&quot;dcg-frontpage-landing-tools__link dcg-shared-product-icon-container dcg-hovered&quot;]/i[@class=&quot;dcg-shared-product-icon dcg-icon-matrix dcg-hovered&quot;]</value>
      <webElementGuid>6a38af80-ecea-4edd-970f-81f473ce4a52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='dcg-main-content-region']/div/section[2]/div/div/a[4]/i</value>
      <webElementGuid>bfdcfc0a-e0b1-4e1f-b964-32ac280744ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>b8aeebea-e82b-4238-a6b6-961ced48c05e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
