<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HasilPerhitungan</name>
   <tag></tag>
   <elementGuidId>7f1644bb-e677-46b9-b6ba-95bade9d31ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-mq-root-block.dcg-hovered.dcg-mq-hasCursor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div[2]/div/div[5]/div[2]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;=0.8333333333&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e522072b-4aa0-4342-99e9-79341c07996c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-mq-root-block dcg-hovered dcg-mq-hasCursor</value>
      <webElementGuid>a258931d-1600-4992-8da1-af897211d144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95d03627-aed8-4bcb-a359-481ab7e7e380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>=0.8333333333​</value>
      <webElementGuid>14cd0b7d-7a37-4691-b97d-3dc1cce238e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-calculator-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-basic-main-wrapper dcg-scientific-calculator dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-basic-main dcg-hovered&quot;]/div[@class=&quot;dcg-basic-list-container dcg-hovered&quot;]/div[@class=&quot;dcg-basic-list dcg-hovered&quot;]/div[@class=&quot;dcg-basic-expression dcg-hovered&quot;]/div[@class=&quot;dcg-exp-output-container dcg-hovered&quot;]/div[@class=&quot;dcg-basic-expression-value dcg-hovered&quot;]/div[@class=&quot;dcg-mq-math-mode dcg-static-mathquill-view dcg-hovered&quot;]/span[@class=&quot;dcg-mq-root-block dcg-hovered dcg-mq-hasCursor&quot;]</value>
      <webElementGuid>8b217bdd-69e8-4d00-9d32-e9226ad02b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div[2]/div/div[5]/div[2]/div/span[2]</value>
      <webElementGuid>2c298772-4ec9-4a3a-83c5-969486ad2ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='equals 0.8 3 3 3 3 3 3 3 3 3'])[1]/following::span[1]</value>
      <webElementGuid>eeef10bb-8b18-4611-8de0-61d0912d1c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::span[2]</value>
      <webElementGuid>183411d1-00fd-40e9-a04b-c1de766c1bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]</value>
      <webElementGuid>bad1ca31-f3c0-4f8c-8c6e-668ac238d6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '=0.8333333333​' or . = '=0.8333333333​')]</value>
      <webElementGuid>e3397c94-65c2-4107-9be7-3d593ce14461</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
