<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number5_Button</name>
   <tag></tag>
   <elementGuidId>99f0f360-b5d9-411d-9c61-0f8acf0e9d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.dcg-keypad-btn.dcg-btn-dark-on-gray.dcg-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;5&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b75e671-cd7d-4fe2-b51f-a108c473aeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4978120f-6701-44e4-85cb-cfce40e5990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcg-keypad-btn dcg-btn-dark-on-gray dcg-hovered</value>
      <webElementGuid>bf24dc2e-24bd-47da-ae0b-59a30518e65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcg-command</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b2df4357-c8b7-40a8-a00e-279a843b582d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>dd24f450-f9c5-4b26-ae20-de979ddfad22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>9671fc09-e569-48ec-bb0e-dfc0e152f71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;dcg-calculator-api-container-v1_10&quot;]/div[@class=&quot;dcg-calc-basic-main-wrapper dcg-scientific-calculator dcg-container dcg-tap-container touchtracking_id_1 dcg-hovered&quot;]/div[@class=&quot;dcg-calc-basic-main dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad-container dcg-hovered&quot;]/div[@class=&quot;dcg-hovered&quot;]/div[@class=&quot;dcg-basic-keypad dcg-do-not-blur dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-row dcg-hovered&quot;]/div[@class=&quot;dcg-keypad-btn-container dcg-hovered&quot;]/span[@class=&quot;dcg-keypad-btn dcg-btn-dark-on-gray dcg-hovered&quot;]</value>
      <webElementGuid>5f824ec4-3c94-4fb9-b7cd-2a8f673e3e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[3]/div[2]/div/div/div[2]/div[6]/span</value>
      <webElementGuid>2894197f-2211-452d-88f8-9ba15cd50793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='π'])[1]/following::span[6]</value>
      <webElementGuid>e3713493-ce7a-48ba-a484-004aa95da852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pi'])[1]/following::span[8]</value>
      <webElementGuid>9c351e35-5d14-4a45-856c-5a2546c42cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='times'])[1]/preceding::span[10]</value>
      <webElementGuid>e4794b32-49ec-49ce-898d-44470543a388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[11]</value>
      <webElementGuid>adc04c5e-ccf4-49bd-8615-9caa2a2620f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/span</value>
      <webElementGuid>f105109a-d00c-4d4b-aced-32d6c8cbe158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '55' or . = '55')]</value>
      <webElementGuid>b76fb0a5-de2f-48e6-9c96-b841d047a334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
